alphagov/search-v2-infrastructure

.devcontainer.json, .gitignore, README.md
This enables users to log in to Terraform Cloud and have their credentials persisted through container rebuilds.
=> Add local Terraform credentials directory and mount

main.tf
- Enable Cloud Resource Manager (prerequisite for enabling Discovery Engine API)
- Refactor into `google_services` resource with array local
=> Enable Cloud Resource Manager

main.tf
Adds the module and runs `gcloud version` through it to verify we can use it with Terraform Cloud.
=> Add `terraform-google-gcloud` module

.devcontainer.json, main.tf, variables.tf
This is a first attempt at provisioning Vertex over the GCP REST APIs.
- Add initial resource for Vertex datastore
- Add REST API provider and remove `gcloud` module (we can't use it)
- Add `gcloud` tooling to devcontainer
=> Use REST API provider to provision Vertex resources

.devcontainer.json, discovery_engine.tf, files/datastore_schema.json, variables.tf
- Make schema creation act as update (as default schema is automatically created with datastore)
- Remove unnecessary variables (the `default_*` IDs can just be hardcoded)
- Fix schema incorrectly specifying params on array rather than field level
- Add ability for devcontainer to mount Google credentials for running Terraform locally
=> Finalise creation of datastore and schema

README.md, service_accounts.tf
Create and configure service accounts, IAM roles, role bindings, and keys for `search-api-v2` to be able to access the Discovery Engine API.
=> Create service accounts for `search-api-v2`

service_accounts.tf
Turns out you can't use wildcards for permission verbs, so manually specifying all verbs for `discoveryengine.documents`.
=> Manually specify permissions for roles

service_accounts.tf
Google service account private keys are base64 encoded, but we'd rather just store the raw value in Secrets Manager.
=> base64decode Google key before persisting

service_accounts.tf
Having them in Secrets Manager as base64 actually allows us to mount them as files more easily.
=> Don't base64 decode Google keys

service_accounts.tf
The pipeline around the external secrets Kubernetes operator tries to be overly "helpful" by treating top-level JSON as individual secrets, when what we _really_ want is the whole JSON as a single entity.
This nests the Google credentials JSON under a top-level key, which we can then extract using the external secrets operator as a single file.
=> Nest Google credentials in SM under a top-level JSON key

discovery_engine.tf, variables.tf
This will be useful for the dev environment, where we may want to have several engines (e.g. one per engineer).
=> Allow specifying multiple engines per environment

service_accounts.tf, variables.tf
We want to create a `dev` environment that has several engines for local use by the team, and doesn't actually have a deployed API. This allows disabling the generation of service account keys (and the import into AWS Secrets Manager) for a given workspace.
=> Allow disabling of SA key generation

terraformcloud/main.tf, terraformcloud/variables.tf
Now that we have validated that we can build a reasonable environment with the example of integration, we want to actually use IaC to define the meta-level resources all the way to Terraform Cloud configuration.
- Add `terraformcloud` subfolder (to be refactored into something nicer later)
- Set up resource definitions for a meta-workspace to contain TF Cloud setup (`search-api-v2-terraformcloud`)
=> Add initial bootstrap configuration for TF Cloud

.devcontainer.json, .gitignore, README.md, terraform/meta/README.md, terraform/meta/main.tf, terraform/meta/variables.tf
- Add Google provider to `meta` module
- Add GCP project resources per environment to `meta` module
- Enable Cloud Resource Manager APIs on all projects
- Add ability for `gcloud` CLI credentials to persist across devcontainer rebuilds
Note: GCP projects have already been created manually previously and the existing projects have been imported into the `meta` workspace state.
=> Manage GCP projects in `meta` module

.github/workflows/lint.yml
This ensures `terraform init` and `terraform validate` are run across all the modules in this repository.
=> Fix CI for new multi-module repo

terraform/meta/main.tf
Enables the following GCP services/APIs that are required to use dynamic credentials with Terraform Cloud:
- IAM
- IAM Credentials
- Security Token Service
=> Enable GCP services for TF Cloud dynamic credentials

terraform/meta/main.tf
This adds the required environment variables to the Terraform Cloud workspaces to be able to use workload identity federation to access GCP.
=> Set up TF Cloud workspaces to use WIF

terraform/meta/main.tf, terraform/meta/variables.tf
This allows the environment workspaces to use identity federation to access AWS resources (specifically, they will need to create Secrets Manager secrets).
- Introduce the concept of "local-only" environments that don't have an API service running on Kubernetes and thus don't need AWS resources created for them
- Access existing AWS identity configuration variable sets and bind them to the environment workspaces (except ones that are "local-only")
=> Associate AWS ID variable sets with TFC workspaces

terraform/meta/main.tf
We've destroyed some resources for testing purposes and GCP won't let you reuse the name of a deleted identity pool as it keeps them around for 30 days post-deletion.
=> Rename GCP identity pool

terraform/discovery_engine/service_accounts.tf
This is now configured in the `meta` module and no longer exists.
=> Remove unneeded IAM dependency

terraform/meta/main.tf
Now that the configuration is relatively stable, we can configure the TF Cloud workspaces to automatically apply the module on VCS merge.
=> Automatically apply from main in env workspaces

terraform/meta/modules/environment/main.tf
We've been iterating on a few things and the provider wound up soft-deleted again and won't re-create with the same name, unfortunately the easiest option of dealing with this is simply changing the name of the created resource.
=> Change GCP ID provider name (again)

terraform/full_environment/service_accounts.tf
These otherwise have a 30 day soft deletion recovery window by default, which means that running a Terraform destroy followed by an apply would fail due to a naming conflict.
=> Force delete AWS SM resources on destroy

terraform/full_environment/discovery_engine.tf, terraform/meta/modules/environment/main.tf, terraform/meta/modules/environment/variables.tf
These are common to all projects, won't change a lot, and make more sense to manage in the `meta` module.
- Add `google_cloud_apis` variable to define set of APIs to enable on all projects
- Use `for_each` to enable GCP APIs
- Set `discoveryengine` API to not disable itself on destroy in `full_environment` module (in preparation for removing it in subsequent commit)
=> Manage all GCP APIs through `meta` module

terraform/full_environment/discovery_engine.tf
The enabling of the `discoveryengine` API is now managed in the `meta` module.
=> Remove management of DE API from `full_environment`

terraform/full_environment/outputs.tf, terraform/modules/google_discovery_engine_restapi/outputs.tf
This adds outputs to the Discovery Engine shared module and the `full_environment` module to reflect the paths on GCP on which the created engine is available.
=> Add outputs for Discovery Engine paths

terraform/meta/modules/environment/variables.tf
These APIs/services will be required for the event pipeline resources we'll create in the `full_environment` module soon.
=> Enable extra APIs for event pipeline

.github/workflows/lint.yml, terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
This updates the schema to reflect that no additional properties should be present in any JSON documents above and beyond those explicitly specified in the schema.
Also updates Github lint workflow to always run even when no relevant
files have been changed (as this is now a required workflow for branch
protection purposes).
=> Datastore schema: disallow additional properties

.github/workflows/schema.yml
This validates the JSON schema for the Google Discovery Engine datastore against the JSON Schema metaschema to make sure it is valid.
=> Add simple validation for JSON schema

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
- Allow `parts` to be nullable
- Require `parts.body` to be non-null (it may be an empty string but not null)
=> Tweak datastore schema

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
We've updated the sync worker to not send through null fields anyway, and Discovery Engine does not support multi-type field syntax.
=> Do not make parts nullable

terraform/meta/modules/environment/main.tf
Changes to the JSON schema should also trigger a workspace re-plan.
=> Amend TFC workspace trigger patterns

terraform/full_environment/service_accounts.tf
This will stay a monolithic single app with worker for now, so there is no point separating the two service accounts. We may split them out again in the future, so keep the two roles but assign them to the same SA.
=> Move to single API key and SA for API

terraform/full_environment/discovery_engine.tf
This adds the paths for datastore and engine to an AWS Secrets Manager secret, for picking up by the Kubernetes platform.
=> Add Discovery Engine configuration to AWS SM

terraform/full_environment/service_accounts.tf
Service account added for GA Analytics team to provide read permissions for search events data
=> Service account to read analytics data

terraform/full_environment/events_ingestion.tf
Gen 2 Functions require extra permissions
=> Additional ppermissions to invoke Cloud Functions

terraform/full_environment/discovery_engine.tf, terraform/full_environment/outputs.tf, terraform/modules/google_discovery_engine_restapi/outputs.tf
This is what we will be using in the API app, so might as well use this instead of the app having to build the path itself.
=> Export serving config path instead of engine

terraform/full_environment/events_ingestion.tf
Terraform will not destroy the US dataset as it insists it is in use. Quick google shows that deleting the underlying tables first, redeploying the dataset to the EU then deploying the tables again should work as a fix.
=> Removing tables prior to redeploying dataset in EU

terraform/full_environment/events_ingestion.tf
Tables were destroyed in the US so that the dataset in the US could be destroyed
Dataset was then recreated in the EU
Now redeploying tables to the EU
=> Redeploying Tables in EU Dataset

terraform/dev_environment/main.tf, terraform/full_environment/discovery_engine.tf, terraform/modules/google_discovery_engine_restapi/main.tf, terraform/modules/google_discovery_engine_restapi/outputs.tf, terraform/modules/google_discovery_engine_restapi/variables.tf
Now that the Discovery Engine API supports creating engines, we need to migrate over to using engines instead of datastores directly.
- Make engine and datastore names configurable separately
- Create engine in `discovery_engine` module
- Move engine-related configuration out of datastore
- Change serving config output to be nested under the engine instead of the datastore
- Configure engine name in dev and full environments
=> Migrate to Discovery Engine engines

terraform/full_environment/discovery_engine.tf, terraform/modules/google_discovery_engine_restapi/outputs.tf
This will allow us to have the app talk to the branch without having to manually construct the branch path in the app.
=> Export datastore default branch into AWS SM

terraform/full_environment_without_events/README.md, terraform/full_environment_without_events/discovery_engine.tf, terraform/full_environment_without_events/main.tf, terraform/full_environment_without_events/outputs.tf, terraform/full_environment_without_events/service_accounts.tf, terraform/full_environment_without_events/variables.tf, terraform/meta/main.tf
This is a temporary module that symlinks or copies the more stable, non-event related resources from the `full_environment` module. This allows us to aggressively iterate on the events ingestion code but only have it deploy to a single (integration) environment.
=> Add `full_environment_without_events` environment module

terraform/meta/main.tf, terraform/meta/modules/environment/main.tf, terraform/meta/modules/environment/variables.tf
Now that we have temporarily split the environments into separate `full_environment` and `full_environment_without_events`, we can confidently auto-apply everywhere again #ContinuousDelivery
=> Always auto-apply TFC workspaces

terraform/full_environment/outputs.tf
This is helpful for debugging whether the right path is generated.
=> Add DE datastore default branch to outputs

terraform/full_environment/events_ingestion.tf
This is causing a re-apply on every unrelated change otherwise because it's automatically added as a property of the remote resource on GCP anyway, and Terraform thinks it needs to remove it.
=> Explicity specify Cloud Functions entrypoint

terraform/full_environment/events_ingestion.tf
The zip files with source code for Cloud Functions functions need to be given unique file names if their content changes, otherwise the Cloud Function won't get redeployed because Terraform thinks it's still pointing at the same file.
(Plus a whole bunch of whitespace fixes)
=> Ensure CF2 source zip files have unique names

terraform/full_environment/files/search-event-schema.json
Removing `pageCategories` field not present in latest definition of user event from Google
=> Removed unused field

terraform/modules/google_discovery_engine_restapi/files/controls/boosts.yml, terraform/modules/google_discovery_engine_restapi/main.tf
These are used to promote or demote documents based on their metadata where we know that certain kinds of documents contain less important/"mainstream" information and get in the way of users finding more relevant content.
This particular configuration is predominantly adapted from one that provided good results during out proof-of-concept phase, which in turn is quite similar to the boosts originally found in Search API's `config/query/boosting.yml`.
=> Add initial set of boosts to Discovery Engine

terraform/modules/google_discovery_engine_restapi/main.tf
This attaches the newly created boost controls to the engine itself.
=> Attach boost controls to Discovery Engine engine

terraform/modules/google_discovery_engine_restapi/main.tf
These are actually a property of the serving config. Whether or not this will work is TBD, but an approach similar to schema creation/updating should do the trick.
=> Attach controls to serving config, not engine

terraform/modules/google_discovery_engine_restapi/main.tf
There seems to be a bug with Discovery Engine that means serving configs can't be updated (and apparently list/get doesn't work either).
Disabling this until we get to the bottom of it to avoid constant apply errors.
=> Disable serving config updating for now

terraform/modules/google_discovery_engine_restapi/files/controls/synonyms.yml, terraform/modules/google_discovery_engine_restapi/main.tf
- Add a YAML config file with a single synonym until we extract a complete list
- Create synonym serving controls based on the config file
=> Add ability to define synonym controls

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
This should be indexable so we can boost on it (for best bets).
=> Make `link` field on documents indexable

terraform/full_environment/evaluator.tf, terraform/full_environment/files/evaluator-schema.json
This adds a BigQuery dataset and table for the evaluation tool to persist feedback to, and a service account, role, and binding to enable it.
=> Add BigQuery setup for evaluation tool

terraform/modules/google_discovery_engine_restapi/main.tf
This creates the serving controls again, this time attaching them to the `default_search` serving config on the datastore (instead of the engine.)
=> Create serving controls and attach to `default_search`

terraform/modules/google_discovery_engine_restapi/main.tf
GCP is still complaining about this not being present, with an ambiguous error message - so try having it in the payload.
=> Try adding updateMask to payload

terraform/meta/main.tf
The events orchestration code is now ready for prime time. This means we can once again use the same full_environment module for all environments.
=> Make all environments use `full_environment` again

terraform/full_environment/events_ingestion.tf
These had been soft-deleted in some environments at one point and are refusing to recreate with their original names #DevOps
=> Rename GCP roles

terraform/modules/google_discovery_engine_restapi/main.tf
This still isn't working as expected, probably due to the precise call the `restapi` client is making.
=> Try fixing serving config update path

terraform/modules/google_discovery_engine_restapi/outputs.tf
Until the bug around being unable to attach serving controls to an engine serving config is fixed, revert to outputting the datastore serving config path from the Discovery Engine module (and change it to point to the search serving config).
=> Output datastore serving config path from DE module

terraform/full_environment/evaluator.tf
The client library needs to be able to read datasets to access the table.
=> Add missing BQ permission for eval tool

terraform/full_environment/evaluator.tf
This doesn't need to be on a table-level (and we seem to need dataset access anyway).
=> Evaluator: Move to dataset-level IAM binding

terraform/meta/modules/environment/main.tf
Project number required as variable for auto eval function
Needs to be made available as an environment variable from /meta
=> Adding project number to the meta module

terraform/dev_environment/variables.tf, terraform/full_environment/automated_evaluation.tf, terraform/full_environment/files/automated_evaluation_default_datasets/config.tftpl, terraform/full_environment/variables.tf
Was using hard coded dev project number within the config.tftpl autoeval
file instead of an environment specific variable.
=> Autoeval project id hardcode fix

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
- Add `organisations`, `topical_events`, `world_locations`, and `manual` fields for use in filtering
- Add comment to clarify that `payload_version` is no longer used but cannot be removed due to API limitations
=> Amend Discovery Engine schema with new fields

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
These belong against the `items`, not the parent array.
=> Fix `indexable` annotations in DE schema

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
The `additional_searchable_text` field is also not used anymore.
=> Add another deprecation comment to schema

terraform/full_environment/events_ingestion.tf
The creation of this bucket was reverted but it failed to delete, leaving TF state in a half-applied state. Re-adding it in temporarily with `force_destroy` set so we can remove it in a subsequent commit and have it properly deleted.
=> Recreate and set `force_destroy` on logs bucket

terraform/full_environment/events_ingestion.tf
This was part of a previous revert but failed to delete, so we set `force_destroy` in 4cf18431c446781a3416d7789296e540d68743ae.
=> Remove `vertex_event_ingestion_error_logs` bucket

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
This will allow us to store some debug-related information to help investigate any issues with content synchronisation.
=> Add `debug` object field to DE schema

terraform/meta/README.md, terraform/meta/main.tf, terraform/meta/modules/environment/main.tf, terraform/meta/modules/environment/variables.tf
- Add "consumer quota override" resources for the number of search
requests per minute and total number of documents across datastores
- Add required `google-beta` provider
- Set reasonable increased values for production (to be reviewed further
before we go fully live)
- Add some documentation and helpful commands for figuring out what the
internal (non-display) naming and units are for quotas
=> Set GCP quotas for Discovery Engine

terraform/full_environment/files/analytics_transfer_function/main.py, terraform/full_environment/files/search-event-schema.json
amended the search-event-schema to add the tagIds repeated field to the search-event BQ table. Amended the SQL to select and insert that in the new tagIds field.
=> ammended schema and sql to select and insert tagIds

terraform/meta/modules/environment/main.tf
The dev environment removal and associated module rename went fine, so we can re-enable auto apply.
=> Re-enable auto apply for TFC workspaces

terraform/modules/google_discovery_engine_restapi/main.tf
Removed the `SEARCH_ADD_ON_LLM` setting from the engine config to disable Advanced LLM features (Search summarisation,Search with follow-ups). These features are not required for GOV.UK Search at this time and enabling it has a consumption cost impact
=> Disabled SEARCH_ADD_ON_LLM in engine config

terraform/meta/main.tf
Now that we're about to go live to all users, increase the quota for search requests per minute to a safe value (to possibly be adjusted downwards later if we're happy we don't need it as high).
=> Increase production DE quota to final-ish value

terraform/meta/main.tf
The current peak is just under 2000qpm, so this should still leave us sufficient headroom for the occasional larger peak.
=> Reduce DE query limit down to 5000qpm

terraform/modules/google_discovery_engine_restapi/files/controls/boosts.yml
We're anticipating this causing some issues by boosting legacy content over some new content to be released today.
=> Remove topical events boost for now

terraform/meta/main.tf, terraform/meta/modules/environment/main.tf, terraform/meta/modules/environment/variables.tf
Instead of all environments auto-applying simultaneously, sets up workspace triggers so that integration/staging/production apply in sequence and only if the "previous" environment applied successfully.
=> "Staged rollout" for TFC environment workspaces

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
This was accidentally set to only be indexable and thus not returned in query results and by extension `search-api-v2`, breaking the ability for Finder Frontend to show whether content is historic.
=> Make `is_historic` field retrievable in schema

terraform/meta/modules/environment/main.tf
This was missing from #252 to make runs actually _run_ as part of a staged rollout.
=> Enable auto-applying on run triggers

terraform/meta/main.tf, terraform/meta/modules/environment/main.tf
The attribute on `tfe_workspace` resource is deprecated and this now needs to live in a separate `tfe_workspace_settings` resource.
=> Move execution mode into `tfe_workspace_settings`

terraform/environment/events_ingestion.tf
Set the initial intraday schedule to every 6 hours and can ramp up further if/when required.
* search -> xx:45 transfer to BQ table -> xx:50 transfer to Vertex
* view-item -> xx:50 transfer to BQ table -> xx:55 transfer to Vertex
Schedule based on current timings - BQ transfer taking ~30 seconds and Vertex import taking between 1-5 mins
Each daily Intraday transfer isn't incremental so includes all data for that day - with deduplication in BQ transfer and Vertex import
=> initial intraday schedule every 6 hours

terraform/modules/google_discovery_engine_restapi/files/servingConfigs/servingConfigs.yml, terraform/modules/google_discovery_engine_restapi/main.tf
2 fixes included:-
* create_method changed to `POST` to match default - https://registry.terraform.io/providers/Mastercard/restapi/latest/docs#create_method
* fixed typo in `synonymsControlIds` in `servingConfigs.yml` configuration file
=> Fixes for vertex error on serving config

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
We originally set up `part_of_taxonomy_tree` with a key property mapping of `category` as that intuitively made sense for an array field dealing with tagging. However, this doesn't actually add any practical value, and results in the field being limited to a maximum of 250 items (which isn't enough for a small long tail of content).
This removes the mapping from the field and just sets the `indexable` property instead so it is treated as a regular field.
=> Unset key property mapping for `part_of_taxonomy_tree`

terraform/environment/discovery_engine.tf, terraform/modules/google_discovery_engine_restapi/main.tf
These have now successfully applied in all environments and can be removed.
=> Remove `import`/`deleted` blocks for datastore

terraform/environment/discovery_engine.tf, terraform/modules/google_discovery_engine_restapi/main.tf, terraform/modules/google_discovery_engine_restapi/variables.tf
This is the next step towards using more of the first party Google provider resources for Vertex AI Search (Vertex AI Agent Builder).
=> Migrate to `google_discovery_engine_search_engine`

terraform/environment/discovery_engine.tf, terraform/modules/google_discovery_engine_restapi/main.tf, terraform/modules/google_discovery_engine_restapi/variables.tf
This set of changes attempts to create the first batch of resources that we want to have against the datastore against the engine too.
- Add engine ID var to restapi module
- Make engine and datastore ID config dynamic from TF resource
- Add initial controls and serving config to engine
=> Add controls and serving config resources to engine

terraform/modules/google_discovery_engine_restapi/main.tf
Turns out any controls created on the default datastore serving config also exist on the default engine serving config, so we don't need to create them again.
=> Remove duplicated controls

terraform/environment/discovery_engine.tf
Sets the serving config used by the AWS SM secret to be the one on the engine rather than the datastore.
=> Use engine for exported serving config path

terraform/modules/google_discovery_engine_restapi/main.tf
The engine change has applied in all envs so this can be taken out.
=> Remove `removed` block after successful apply

terraform/modules/google_discovery_engine_restapi/main.tf
As with the serving config changes, this should not actually change anything under the hood as these resources are available identically on both the engine and the datastore in a "symlink" sort of fashion.
=> Migrate controls to live on engine, not datastore

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
We have been using manual boosting and sorting on the `public_timestamp` field as an integer until now.
Discovery Engine now supports datetime fields in RFC3339 format for both a new freshness boosting feature as well as sorting, so we should be able to deprecate the existing `public_timestamp` field and use this one going forwards.
=> Add `public_timestamp_datetime` field to schema

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
This reverts #261 as it turns out removing an existing key property mapping from a field is not a valid schema operation and it's causing schema apply issues.
=> Re-add `category` key property mapping

terraform/modules/google_discovery_engine_restapi/files/datastore_schema.json
This is implied by the key property mapping anyway and apparently conflicts with it.
=> Remove `indexable` annotation from field

terraform/environment/service_accounts.tf
We originally set up two separate IAM roles for Search API v2 to access Discovery Engine, with the idea that there may be two completely separate deployments handling the synchronisation and the querying responsibilities respectively.
This never ended up being the case, and there's no reason to have two separate roles assigned to the same service account, so this change simplifies the two roles into one.
=> Combine Search API v2 IAM roles

terraform/environment/service_accounts.tf
This should be `id` (the fully qualified ID), not the pure role ID.
=> Fix incorrect use of `role_id` in IAM binding

terraform/environment/outputs.tf, terraform/environment/prototype.tf
We'll soon start working on a UI prototype for some upcoming interface improvements for search.
This will (probably) live on Heroku, and get its own set of keys to access GCP and relevant Discovery Engine resources on a read-only basis.
For now, it gets the minimum set of permissions necessary to perform search and autocomplete requests.
=> Add service account for UI prototype

terraform/environment/outputs.tf
This is explicitly required to allow Terraform to output this value.
=> Mark prototype key output as sensitive

terraform/environment/outputs.tf, terraform/environment/prototype.tf
We want to be able to experiment with some advanced Vertex AI Search features in the UI prototype. These come at a cost, and we've specifically disabled them in the production engine to make sure we don't accidentally get charged.
This creates a new engine with the features enabled (enterprise tier and LLM add-on) specifically for use by the UI prototype, leaving the existing production engine unchanged.
=> Add separate engine for UI prototype

terraform/modules/google_discovery_engine_restapi/main.tf
Added Terraform code to set the default completion configuration for autocomplete with the following settings:-
* matchingOrder: out-of-order
* maxSuggestions: 5
* minPrefixLength: 3
=> Added TF for default completion configuration

terraform/environment/discovery_engine.tf
Some properties of some resources on Vertex AI Search can permanently change based on tangentially related changes to other resources, leading to Terraform state drift.
For example, we created a recommendation engine on integration for testing purposes, and it permanently changed the internal state of the datastore it was attached to (despite the engine since having been deleted).
This ignores any post-creation changes to the `solution_types` property to mitigate any consequences of this undesired behaviour (in this case, Terraform trying to recreate the resource as it cannot return the field back to its original state).
=> Ignore datastore `solution_types` property drift

terraform/modules/google_discovery_engine_restapi/main.tf
This will become the primary serving config used by site search, with controls managed by Search Admin.
=> Add new `site_search` serving config

terraform/modules/google_discovery_engine_restapi/main.tf
This failed with a missing `displayName` at the apply stage
=> Fix new serving config

terraform/environment/discovery_engine.tf, terraform/modules/google_discovery_engine_restapi/main.tf, terraform/modules/google_discovery_engine_restapi/variables.tf
* Added variable for storage_bucket_name and passed to discovery_engine module
* Added restapi_object for denylist
Had explored using data source for denylist artifact but it made more complex with no added advantages
=> Added restapi_object for denylist

terraform/environment/service_accounts.tf
This is needed to use the completion API on VAIS.
=> Add `completeQuery` permission to API service account

terraform/environment/evaluator.tf
We want this data to stick around on production even when we delete all other resources.
=> Protect evaluation BQ data from deletion

terraform/meta/modules/environment/main.tf
This adds the shared Google Group as an owner to all the GCP projects managed by the `meta` module.
=> Add GOV.UK GCP access group to GCP projects

terraform/environment/files/automated_evaluation/main.py
When going through this script to figure out what it does ahead of porting it to Ruby, I noticed some functions that weren't being used, and some code paths that will never actually be executed.
See commits for details. I'm reasonably confident with the first commit, but the second one which removes the code related to testing autocomplete results I'm a little unsure about.
This doesn't strictly need to be done, but it should make the process of porting to Ruby a little easier.
=> Remove some unused code in the auto eval script

terraform/environment/discovery_engine.tf
This adds the GCP project's ID to the AWS Secrets Manager secret for Search API v2, to allow us to specify the right BigQuery resources for importing user event data.
=> Add `GOOGLE_CLOUD_PROJECT_ID` to AWS SM secret

terraform/environment/service_accounts.tf
These are needed as we move some tasks from running as GCP Cloud Functions to being Rake tasks in the API app itself.
=> Add extra permissions to API service account
