.devcontainer.json, main.tf, variables.tf
- Add variables for GCP project and region
- Enable Discovery Engine API
- Enable `formatOnSave` for devcontainer
=> Initial setup for GCP

.github/workflows/lint.yml, main.tf
- Add formatting, linting and validation along the lines of
`alphagov/govuk-infrastructure` (minus the multi-directory handling)
- Fix missing provider version constraint
=> Set up Github Actions linting/validation

main.tf
- Correct URL for IAM credentials API enablement
- Manually specify object ID for restapi resource
=> Fix apply issues

main.tf
Instead of generating a new one against the service account
=> Use Google provider's own API token

main.tf
=> Fix incorrect Google API path

main.tf, variables.tf
- Tweak data store resource
- Update "Vertex" references to "Discovery Engine" (as that is what all the APIs are called internally)
=> Continue implementing discovery engine datastore resource

discovery_engine.tf, files/datastore_schema.json, variables.tf
- Add initial metadata schema as JSON
- Add `restapi_object` resource for schema creation
- Tweak variable names for consistency
=> Add initial metadata schema

README.md, discovery_engine.tf, main.tf, variables.tf
- Flesh out README
- Rename and refactor some resources to be more clear
=> General cleanup and documentation

discovery_engine.tf
The `dataStoreId` needs to be in the payload, not the query params.
=> Fix datastore creation

service_accounts.tf
- Enable IAM API as this is required for the IAM resources
- Make IAM resources depend on enabled IAM API
=> Enable IAM API for project

service_accounts.tf
Make IAM bindings refer to role IDs and SA member fields
=> Fix incorrect manual references to IAM resources

terraform/meta/main.tf
- Set up a GCP service account with editor role per environment project
- Set the service account up for identity federation
=> Create per-project service accounts for TF Cloud

terraform/meta/main.tf
- Fetch Github OAuth provider resource as data
- Set up the repository details for the environment workspace resource
=> Set up VCS connection for environment workspaces

terraform/discovery_engine/discovery_engine.tf, terraform/discovery_engine/main.tf, terraform/discovery_engine/service_accounts.tf, terraform/discovery_engine/variables.tf, terraform/modules/google_discovery_engine_restapi/main.tf, terraform/modules/google_discovery_engine_restapi/variables.tf
In preparation for setting up a dev environment
=> Modularise Discovery Engine resources

terraform/meta/modules/environment/main.tf
- Automatically trigger plan+apply if any Terraform files change in the environment's module or any shared module
=> Add triggers to TF Cloud workspaces

terraform/dev_environment/main.tf, terraform/dev_environment/variables.tf
- Add basic module to set up dev engines
- Configure one engine per developer for now
=> Initial setup of development engines

terraform/full_environment/events_ingestion.tf
- Removing time partition temporarily from bq vertex tables
- Renaming cloud function to be unique
=> Events cloud function updates

terraform/full_environment/events_ingestion.tf
Attribute changed from .member to .email
=> Updating function service account email

terraform/full_environment/events_ingestion.tf
Removing vpc egress settings config from cloud function - not required
Terraform formatting
=> Removing VPC settings from function

terraform/full_environment/files/analytics_transfer_function/main.py
-Added an argument to the callback to handle returned futures
=> main.py callback was incorrectly handling futures

terraform/full_environment/events_ingestion.tf
Location was set to `US` by default instead of `eu-west-2`
=> Location was incorrect for BQ datasets

terraform/full_environment/events_ingestion.tf, terraform/full_environment/files/analytics_transfer_function/main.py
Using as_completed function to block the query until complete
=> Fixing futures python problem

terraform/full_environment/files/analytics_transfer_function/main.py
Adding try except and .result() so when bq job completes then only will function return success
=> Function returning success when async bq completes

terraform/full_environment/events_ingestion.tf, terraform/full_environment/files/analytics_transfer_function/main.py
Also adding default body to scheduler
=> Switching from GET back to post

.devcontainer.json, terraform/full_environment/events_ingestion.tf, terraform/full_environment/files/vertex_events_push/main.py, terraform/full_environment/files/vertex_events_push/requirements.txt
- Terraform to deploy function and necessary resources to run
function that will transfer vertex BQ data to vertex datastore.
=> Vertex BQ -> Vertex Datastore Transfer

terraform/full_environment/events_ingestion.tf, terraform/full_environment/files/vertex_events_push/main.py
Request object provided in function definition
=> vertex_events_push needs an argument

terraform/full_environment/files/analytics_transfer_function/main.py
`documents` field has changed in the schema in line with google document
changes. Reflecting the schema change in the SQL
=> Amending view-item SQL

terraform/meta/modules/environment/main.tf
A plan should be kicked off for any change under the `files/` directory in modules
=> Update TFC workspace trigger patterns

terraform/full_environment/files/analytics_transfer_function/main.py, terraform/full_environment/files/search-event-schema.json
Search field has changed in the Google user event schema
Making changes to SQL and table definition to reflect these changes
=> Google Event Schema Changes

terraform/full_environment_without_events/evaluator.tf, terraform/full_environment_without_events/files
This can go to staging and production now.
=> Symlink evaluator resources into full env without events

terraform/modules/google_discovery_engine_restapi/main.tf
This is in anticipation of creating them again as part of the datastore.
=> Remove engine serving controls

terraform/modules/google_discovery_engine_restapi/main.tf
It looks like this needs to be in snake_case rather than camelCase...
=> Try underscoring update mask

terraform/full_environment/events_ingestion.tf, terraform/full_environment/files/automated_evaluation_default_datasets/qrels.csv, terraform/full_environment/files/automated_evaluation_default_datasets/report.csv
- changed the dependency of table to external file from gcs bucket
- sample data generated for external tables
=> Changes to enable external BQ tables for auto test

terraform/full_environment/automated_evaluation.tf
managed folders removed, storage object create and update added
=> permissions updates:

terraform/modules/google_discovery_engine_restapi/files/controls/boosts.yml
This revised set of boost specs should provide better results compared to the old ones which were just "lifted and shifted" from v1.
=> Change boost specs

terraform/modules/google_discovery_engine_restapi/main.tf
These were disabled previously so the changes in #236 had no effect...
=> Actually enable boosts again

terraform/meta/main.tf, terraform/meta/modules/environment/main.tf, terraform/meta/modules/environment/variables.tf
(and replace with titleised name)
=> Remove unnecessary `display_name` for envs

terraform/environment/events_ingestion.tf, terraform/environment/files/analytics_transfer_function/main.py
Added support for intraday events:-
* Added 2 intraday events tables in BQ
* Added 2 additional intraday queries to the existing analytics_transfer_function - minor refactoring to support date deltas other than yesterday
* Added 2 additional cloud scheduler tasks for intraday BQ data transfer
* Added 2 additional cloud scheduler takks for intraday Vertex import
=> Added support for intraday events

terraform/environment/events_ingestion.tf
`Schedule or time zone is invalid` error due to invalid cron pattern - changed for far future cron pattern instead
=> Fix for disabled cron pattern in scheduler

terraform/environment/files/vertex_events_push/main.py
Added support for intraday import to use day 0 partition
=> Added support for intraday import to use day 0 partition

terraform/modules/google_discovery_engine_restapi/files/servingConfigs/servingConfigs.yml, terraform/modules/google_discovery_engine_restapi/main.tf
Added Terraform for additional serving config:-
* main.tf - added additional serving config resource
* servingConfigs.yaml - added configuration for additional serving configs including associated controls
=> Added Terraform for additional serving config

terraform/environment/automated_evaluation.tf
Added the new implicit judgement list and changed the cron pattern of the daily scheduler to run at 07:00 each day
=> Added new judgement list and changed daily schedule

terraform/modules/google_discovery_engine_restapi/main.tf
This _should_ be as simple as changing the endpoints to be against the engines (as everything already seems to be "symlinked" there anyway). Also removes the setting up of a separate serving config on the datastore, replacing it with just one on the engine.
=> Migrate serving config/controls to engine

terraform/modules/google_discovery_engine_restapi/main.tf
Add additional properties to make the REST API client happy
=> Fix `completionConfig` failing to apply

terraform/environment/events_ingestion.tf, terraform/environment/files/analytics_transfer_function/main.py
Adding support for ingesting External Link GA4 data into Vertex. These documents already exist in 'search' events and this change is to add additional 'view-item' events - existing 'view-item' events only cover GOV.UK pages.
These are being loaded into seperate BQ tables to isolate them from existing 'view-item' events but are based on and ingested into Vertex using the same 'view-item' schema.
* 2 new BQ tables (Daily and Intraday)
* 2 new Scheduler transfer instances from GA4 BQ -> search environment BQ(Daily and Intraday)
* 2 new Scheduler VAIS ingest instances (Daily and Intraday)
* 2 new BQ queries in Python to be executed to extract the appropriate GA4 data (Daily and Intraday)
=> Added TF and Python for External Link event ingestion

terraform/modules/google_discovery_engine_restapi/main.tf
Reworked and added datastore field to boostControl
=> Vais regression issue

terraform/environment/discovery_engine.tf, terraform/modules/google_discovery_engine_restapi/main.tf, terraform/modules/google_discovery_engine_restapi/variables.tf
Added full datastore path and non-zero boost fallback
=> Added full datastore path and non-zero boost fallback

terraform/modules/google_discovery_engine_restapi/main.tf
=> Fixed dataStore

terraform/modules/google_discovery_engine_restapi/main.tf
Changing syntax for jsonencode
=> Fix for denylist control

terraform/environment/files/automated_evaluation/main.py
This reverts #313.
It seems like this is making the cloud function fail for some reason, so let's add it back in.
=> Revert auto eval code removal
